name: 不具合レポート
description: 不具合レポート
title: "[Bug]: "
labels: ["バグ"]
body:
  - type: markdown
    attributes:
      value: |
        再現に必要な情報を簡潔に記載してください。
  - type: dropdown
    id: devicetype
    attributes:
      label: ■端末種別
      options:
        - iOS
        - iPadOS
        - Android
        - Windows
        - macOS
        - その他
    validations:
      required: true
  - type: input
    id: devicename
    attributes:
      label: ■端末名
      placeholder: iPhone 14 Pro
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: ■アプリバージョン
      placeholder: 1.0.0(10)
    validations:
      required: true
  - type: textarea
    id: procedure
    attributes:
      label: ■実施手順
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    id: actual-result
    attributes:
      label: ■実際の結果
      placeholder: 発生した現象を簡潔に記載
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: ■期待される結果
      placeholder: 本来期待される動作を簡潔に記載
    validations:
      required: true
  - type: input
    id: timestamp
    attributes:
      label: ■発生日時
      description: 形式：2025-01-01 00:00
      placeholder: 2025-01-01 00:00
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: ■補足情報
      description: 再現に必要な追加情報があれば記載
      placeholder: 再現条件や環境固有の設定など
    validations:
      required: false
